{
  "type": "record",
  "name": "Client",
  "namespace": "org.example.avro",
  "fields": [
    { "name": "id", "type": "int" },
    { "name": "firstName", "type": "string" },
    { "name": "lastName", "type": "string" },
    { "name": "address", "type": "Address" },
    {
      "name": "clientType",
      "type": {
        "type": "enum",
        "name": "ClientType",
        "symbols": ["GOLD", "SILVER", "BRONZE"]
      }
    },
    { "name": "archived", "type": "boolean" },
    { "name": "rents", "type": "int" }
  ]
}
